site_name: parshift
repo_url: https://github.com/bdfsaraiva/parshift
site_url: https://bdfsaraiva.github.io/parshif
site_description: description
site_author: Bruno D. Ferreira-Saraiva
use_directory_urls: false


theme:
  custom_dir: images/
  name: material
  icon:
    logo: material/library
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: icon.png
  logo: icon.png
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow


nav:
  - Home: index.md
  - Info: info.md

copyright: Copyright &copy; 2022 Maintained by <a href="https://github.com/bdfsaraiva">Bruno D. Ferreira-Saraiva</a>.
