site_name: BERTopic
repo_url: https://github.com/bdfsaraiva/py-Participation-Shifts
site_url: https://bdfsaraiva.github.io/py-Participation-Shifts/
site_description: Leveraging BERT and a class-based TF-IDF to create easily interpretable topics.
site_author: Bruno D. Ferreira-Saraiva
use_directory_urls: false
extra_css:
#   - stylesheets/extra.css


nav:
  - Home: index.md
  - The Algorithm: #algorithm/algorithm.md
  - Getting Started:
  
theme:
  custom_dir: images/
  name: material
  icon:
    logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: groups_2_black_36dp.svg
  logo: groups_2_black_36dp.svg
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
