site_name: ParShift
repo_url: https://github.com/bdfsaraiva/parshift
site_url: https://bdfsaraiva.github.io/parshift
site_description: description
site_author: Bruno D. Ferreira-Saraiva
use_directory_urls: false


theme:
  custom_dir: images/
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
  font:
    text: Roboto
    code: Fira Code
  favicon: icon.png
  logo: icon.png
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow


plugins:
- search:
    lang: en

- mkdocstrings

nav:
  - Home: index.md
  - API:
    - Annotation: api/annotation.md
    - Conditional Probabilities: api/conditional_probabilities.md
    - Plotting: api/plotting.md

copyright: Copyright &copy; 2023 Maintained by <a href="https://github.com/bdfsaraiva">Bruno D. Ferreira-Saraiva</a>.
