site_name: ParShift
repo_url: https://github.com/bdfsaraiva/parshift
site_url: https://bdfsaraiva.github.io/parshift
site_description:
  ParShift is a Python package based on Gibson's framework for the analysis of
  conversational sequences.
site_author: Bruno D. Ferreira-Saraiva
watch:
  - ../parshift

theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
  font:
    text: Roboto
    code: Fira Code
  favicon: images/icon.png
  logo: images/icon_g.png
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow

plugins:
- search:
    lang: en
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [..]
        import:
        - https://docs.python.org/3/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        options:
          docstring_style: google
          show_root_toc_entry: false
          show_submodules: no
          heading_level: 2
          line_length: 88
          show_signature_annotations: true
          separate_signature: true

nav:
  - Home: index.md
  - Reference: reference.md
  - Development: dev.md

copyright: Copyright &copy; 2023-2025 Maintained by <a href="https://github.com/bdfsaraiva">Bruno D. Ferreira-Saraiva</a>.
