name: gh-deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name : Install requirements
        run : |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          python -m pip install -e .[dev]
          
      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy
      - name: Run tests and collect coverage
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3.1.1
        



