name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
        
      - name : Install requirements
        run : |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          python -m pip install -e .[dev]
          
      - name: Run black formatter
        uses: black .
        
      - name: Run tests and collect coverage
        run: pytest --cov=./ --cov-report=xml
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.1
        
      - name: MkDocs gh-deploy
        run: |
          git pull
          mkdocs gh-deploy
          
      
        



